### ISSUE TITLE
cpasbien.cm

### ISSUE THREAD

**Issue by bubuleur** [rik91/script.quasar.cpasbien-rik91#1]
Bonjour,
je viens vers vous pour le changement de l'adresse en cpasbien.cm
faut il le changer dans les paramétrés pour que ça marche ?
Parce que avec quasar il me trouve plus rien si je laisse cpasbien.io
Cordialement
Merci pour votre travail

**Comment by rik91** [comment]
Voila,
Comme le provider t411, j'ai publié un version 1.3.6b avec la nouvelle URL.
Et en effet, tu peux modifier l'URL directement dans les paramètres du plugin.
D'ailleurs c'est ce qui y a de mieux à faire pour une mise à jour, pour les même raison que celles évoquées dans le repository du plugin T411.

Rik91
